name: build
on:
    push:
    pull_request:
    workflow_dispatch:
        
jobs:
    build:
        name: Build
        runs-on: ubuntu-20.04
        steps:

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.7.2'
            - uses: actions/checkout@v3
            - name: Install Python dependencies
              run: python -m pip install --upgrade pip && pip install -r requirements.txt
            - name: Lint
              run: make lint
            - name: Beautify
              run: make beautify
            - name: Check for code differences
              run: git diff --exit-code

            - name: Run Trivy vulnerability scanner in repo mode
              uses: aquasecurity/trivy-action@0.20.0
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL'
            
            - name: Connecting to JFrog
              uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: ${{ secrets.JF_URL }}
                JF_USER: ${{ secrets.JF_USER }}
                JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

            - name: Upload Trivy scan results to JFrog
              run: curl -u ${JF_USER}:${JF_PASSWORD} -X PUT ${JF_URL}/trivy-results.sarif -T trivy-results.sarif
              env:
                JF_URL: ${{ secrets.JF_URL }}
                JF_USER: ${{ secrets.JF_USER }}
                JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
