name: build
on:
    push:
    pull_request:
    workflow_dispatch:
        
jobs:
    build:
        name: Build
        runs-on: ubuntu-20.04
        steps:

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.7.2'
            - uses: actions/checkout@v3
            - name: Install Python dependencies
              run: python -m pip install --upgrade pip && pip install -r requirements.txt

            - name: Run Trivy vulnerability scanner in repo mode
              uses: aquasecurity/trivy-action@0.20.0
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL'

            - name: Upload Trivy scan results to JFrog
              run: curl -H "X-JFrog-Art-Api:${JF_PASSWORD}" -X PUT ${JF_URL}/trivy-results.sarif -F "file=@trivy-results.sarif" 
              env:
                JF_URL: ${{ secrets.JF_URL }}
                JF_USER: ${{ secrets.JF_USER }}
                JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
